services:
    wg_universaldatatable.serializer.method:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
    wg_universaldatatable.serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
    wg_universaldatatable.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - [@wg_universaldatatable.serializer.method]
            - [@wg_universaldatatable.serializer.encoder.json]
    wg_universaldatatable.twig.extension:
        class: Wg\UniversalDataTableBundle\Twig\DataTableTwigExtension
        arguments: [@translator]
        tags:
            - { name: twig.extension }
    wg_universaldatatable.query:
        class: Wg\UniversalDataTableBundle\DataTable\Data\DataTableDataManager
        arguments: [@request_stack, @wg_universaldatatable.serializer]
